### ISSUE TITLE
[Bug]: Unable to add background image via CSS 

### ISSUE THREAD

**Issue by patrickbjohnson** [uicrooks/shopify-theme-lab#112]
### Operating system

Mac OS

### Node.js version

12.18

### Shopify CLI version

2.0

### Version

3 (Legacy)

### Details

Attempting to reference an image within the assets folder in our CSS to create a hard-coded background image but its failing. Any suggestions?

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
It's not possible to add an image (from the assets directory) with a relative path to the  CSS inside the `src` directory. Shopify uploads all assets to a CDN and generates a random path for the assets. Webpack has no way of knowing what that path might be.  There are a couple of options to circumvent this:

1. If your image is small (a couple of kb), you can convert it to base64 and embed it directly into your CSS file. There're some online tools for that.
2. You can upload your image to Shopify files and add the absolute URL to your CSS.
![screen](https://user-images.githubusercontent.com/68379148/127181348-dbf0b0f0-18b9-4cb2-9f1d-e79c19196238.png)
3. You can create a snippet file with a style tag and define your styling there. It's pretty much the same process as with Local fonts. See the [Local fonts docs page](https://themelab.uicrooks.com/guide/assets.html#local-fonts)

**Comment by TomJacobsUK** [comment]
> It's not possible to add an image (from the assets directory) with a relative path to the CSS inside the `src` directory. Shopify uploads all assets to a CDN and generates a random path for the assets. Webpack has no way of knowing what that path might be.

The CDN that Shopify generates isn't that random when you account for the CSS file being in the same location. A background URL can reference a static asset relatively by using ``background-image:URL(some.static.jpg);``

Assets that need to be run via Webpack can use resolve alias to locate the files through Webpack, the assets that are generated are moved to the asset directory and relatively referenced too, depending on your config it can also base encode certain assets based on file size.

Great toolset btw was in the process of building my own, but I look to contribute to this project instead.
