### ISSUE TITLE
Question: does this affect SEO in any way?

### ISSUE THREAD

**Issue by loicnestler** [uicrooks/shopify-theme-lab#113]
### Operating system

//

### Node.js version

//

### Shopify CLI version

//

### Version

4 (Current)

### Details

Not a bug but the issue template limits me to creating a bug-report. 

I’m quite new to both Vue and Shopify and my question is, if this affects SEO in some way (as vue gets rendered client-side, similar to React) or if the vue templates are getting statically rendered to HTML on build?

Thanks in regards! 

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
Liquid/JSON templates are rendered to HTML. Vue components are rendered during the client-side execution.

But all modern search engines should be able to crawl sites with client-site generated content.

When in doubt you can use the `renderless` pattern for critical parts of your page.
Here's an example from the foundation theme
