### ISSUE TITLE
[Bug]: Fonts return "Failed to decode downloaded font" when uploaded following the docs

### ISSUE THREAD

**Issue by ineptian** [uicrooks/shopify-theme-lab#116]
### Operating system

Windows 10

### Node.js version

15.5.0

### Shopify CLI version

2.1.0

### Browsers

Chrome

### Version

4 (Current)

### Details

When adding fonts to my assets folder, and then referencing per the docs I get some errors.

It looks like the fonts might be being uploaded to shopify as the wrong type of file?

![image](https://user-images.githubusercontent.com/7462616/127704594-3d61b036-91ab-4ece-a071-1d285258c17d.png)

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
This is a Shopify CLI bug. Currently, all binary file uploads are broken (images, fonts etc). Here's a [comment from me on a similar issue in the Shopify CLI Repo](https://github.com/Shopify/shopify-cli/issues/1401#issuecomment-891127561)

**Comment by sergejcodes** [comment]
This issue should now be fixed with the latest Shopify CLI [2.3.0](https://github.com/Shopify/shopify-cli/blob/main/CHANGELOG.md#version-230) release.
