### ISSUE TITLE
[Question]: Installing add-ons

### ISSUE THREAD

**Issue by ammyno** [uicrooks/shopify-theme-lab#119]
### Operating system

Windows 10

### Node.js version

14.0.0

### Shopify CLI version

2.0.0

### Version

3 (Legacy)

### Details

Hello, i've installed an add-on "Judgme App" to be more exact but everytime I enable it I get an javascript error in the browser "Uncaught SyntaxError: 59" .  

I'm assuming this is because the add-on is installing a script inside my product.liquid page.

Is there anyway to make this work ? ( I only have this problem after I build the project , on dev is working fine )

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
It seems this plugin has a manual installation method, where you can copy the render snippets `{% render '...' %}`

You can try to do something like [this](https://github.com/uicrooks/shopify-foundation-theme/blob/master/shopify/layout/theme.liquid#L33-L40) where you check for the `product` template and insert the snippet outside of the `<div id="app"></div>` or create a specific snippet template for the product page.

**Comment by ammyno** [comment]
Figure it out

You need to replace some <style> tags that gets echoed in the judgeme_widgets.liquid with 
` {{ product.metafields.judgeme.widget | replace : "<style class='jdgm-temp-hiding-style'>" , "<!--" | replace: "</style>" , "-->" }}`
