### ISSUE TITLE
[Request]: Can I edit in shopify Backstage

### ISSUE THREAD

**Issue by Kusou1** [uicrooks/shopify-theme-lab#140]
### Operating system

mac m1

### Node.js version

14.18.0

### Shopify CLI version

2.7.1

### Browsers

Chrome

### Version

4 (Current)

### Details

At present, my store uses shopify-theme-lab, but I found a problem, because the vue file is packaged and then published online. If I want to change a picture in the shopify background after publishing, then this The structure does not seem to be established, I need to pull it down and repackage it before pushing，I would like to ask if there is any solution

### Notice

- [X] I read the notice

**Comment by Kusou1** [comment]
thank you very much!🙏🏻

**Comment by haotan19** [comment]
I am not sure this is a bug. 
After you have set an image on Shopify (using Shopify's `image_picker`), The image settings will be updated on the `templates/[your-page].json`

When you are in development mode, I am sure you can **open the Shopify code editor on the editor/customize page**. Copy the settings with image links, and put them in your `.json` file. 

**In short:**
In development mode, remember to download your settings from Shopify first before you deploy the theme.

**Comment by Kusou1** [comment]
thank，At first I thought it would not be updated, but later found out that it would be updated @haotan19
