### ISSUE TITLE
Documentation is right? OS2.0 are available on any development store created after June 29, 2021.

### ISSUE THREAD

**Issue by sk29110** [uicrooks/shopify-theme-lab#144]
### Operating system

any os

### Node.js version

any version

### Shopify CLI version

any version

### Browsers

Chrome

### Version

4 (Current)

### Modifications

Online Store 2.0 features are available on any development store created after June 29, 2021.

Is this correct? It seems if I have a production store running since last year I need to transfer my domain to new store? I doubt it but from this documentation people will think like that. 

### Details

Online Store 2.0 features are available on any development store created after June 29, 2021.

Is this correct? It seems if I have a production store running since last year I need to transfer my domain to new store? I doubt it but from this documentation people will think like that. 

If the documentation is not correct please fix this.

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
When Shopify released the 2.0 functionality it was only working with stores created after that date. The notice is actually taken from the official Shopify docs. Apparently they removed the notice, so maybe now it also works with older stores? I'll test it.

**Comment by sk29110** [comment]
I see. I actually reached out with shopify support and confirmed the os2.0
functionality should be working on old stores too.

Thanks and have a good week!
Shinya

**Comment by sergejcodes** [comment]
Removed notice from the docs
