### ISSUE TITLE
[Question]: Add App and/or Filters

### ISSUE THREAD

**Issue by nicoagp** [uicrooks/shopify-theme-lab#172]
### Operating system

Mac

### Node.js version

16

### Shopify CLI version

2

### Browsers

Chrome

### Version

4 (Current)

### Details

I am trying to install an app ([boostcommerce](https://help.boostcommerce.net/article/451-manual-setup-instruction) filters) manually and got stuck several times mainly because I think it relies on normal shopify structure. Has anyone install this app before? or another similar app ?

Any recommendation with filters using this repo/project/structure ? 

Thank you!

### Notice

- [X] I read the notice

**Comment by lukecharle** [comment]
You should be fine using it. Once you install the app it will have installed files required. Do a shopify pull then update your `webpack.config.js` to ignore the files needed. For example here I've made sure it doesn't delete a file containing `algolia_config`. This will ensure when running `npm run start` it won't then remove these files you retrieved doing shopify pull.

```
new CleanWebpackPlugin({
    cleanOnceBeforeBuildPatterns: ['**/*', '!*static*', '!*algolia_config*'],
}),
```
