### ISSUE TITLE
Vue Router?

### ISSUE THREAD

**Issue by camwhite** [uicrooks/shopify-theme-lab#42]
### Is your feature request related to a problem? Please describe.

Not really, we just want to use the router.

### Describe the solution you'd like

A `/routes` directory very much like the store is setup.

### Additional context

I  would like a better understanding of how routing currently happens.

**Comment by sergejcodes** [comment]
Hi there Cameron 👋

This isn't a single-page app. It uses the default Shopify routing, all files inside `shopify/templates`  are basically your "routes" these files are rendered on the server. 

You can find some additional info in the [Shopify template docs](https://shopify.dev/docs/themes/theme-templates). 

While you could technically implement a `Vue router`, it isn't really suited for this project.

**Comment by camwhite** [comment]
Gotcha thanks for following up!
