### ISSUE TITLE
Mention stylelint-scss support in instructions

### ISSUE THREAD

**Issue by james0r** [uicrooks/shopify-theme-lab#65]
https://www.npmjs.com/package/stylelint-scss

I added this to my fork because I have SCSS enabled by default, but it'd probably be nice to know for those adding SCSS support to shopify-theme-lab via the SCSS install instructions.

Without stylelint-scss and the rules change, you get a huge outpouring of warnings and it breaks your build. Really took me for a ride lol.

Nice learning exp though!

**Comment by sergejcodes** [comment]
Not sure what you mean. I don't have any issues migrating to SCSS and using the default rule-set provided by stylelint. `stylelint-scss` actually enforces even stricter linting rules, than the defaults in vanilla stylelint. SCSS should work out of the box with stylelint. Can you provide some examples of what exactly didn't work?

**Comment by james0r** [comment]
> Not sure what you mean. I don't have any issues migrating to SCSS and using the default rule-set provided by stylelint. `stylelint-scss` actually enforces even stricter linting rules, than the defaults in vanilla stylelint. SCSS should work out of the box with stylelint. Can you provide some examples of what exactly didn't work?

Yeah not sure what if anything I did that deviated from your SCSS install instructions. Just added @mixins in the main.scss and it went bonkers. I'll do a minimal reproduction later and see if it happens again.

**Comment by sergejcodes** [comment]
The issue was `at-rule-no-unknown` ruleset inside the stylelint config. Deactivated it completely in the latest release.  634bfc8 I tested it with some `SCSS` code without installing `stylelint-scss` and everything worked. Of course for more sophisticated linting rules for `SCSS` you can always install `stylelint-scss`
