### ISSUE TITLE
Conflict with @shopify alias

### ISSUE THREAD

**Issue by ccanete** [uicrooks/shopify-theme-lab#77]
Hi @sergejcodes 

The new `@shopify` alias in webpack comes into conflict if you add one of the [shopify theme-scripts](https://github.com/Shopify/theme-scripts) to your app.

I'm using the [@shopify/theme-images](https://github.com/Shopify/theme-scripts/blob/master/packages/theme-images/README.md) library for responsive images and webpack fails to build the project when I import the package.

Link to the config issue:
https://github.com/uicrooks/shopify-theme-lab/blob/7dea52b2018a942f11ba7d261c5eb42c6517fb6c/.config/webpack/webpack.common.js#L18

I don't know if there is a way to avoid webpack alias when importing the lib.

One solution would be to change the alias.

I removed the alias from my project but it could happen to someone else. I just wanted to share this.

Thanks for your work 💪💪💪

**Comment by sergejcodes** [comment]
Hi 👋,

thanks for bringing it up. I'm changing the alias in the latest release
