### ISSUE TITLE
Using v-lazy directive error

### ISSUE THREAD

**Issue by schellenbergk** [uicrooks/shopify-theme-lab#86]
After adding `vue-lazyload` and in `main.js`:

```
import VueLazyload from "vue-lazyload";
...
Vue.use(VueLazyload);
```

then as soon as you add `<img v-lazy="...` in any template, it causes an error in the console:

```
Failed to generate render function:

SyntaxError: Unexpected token '}' in ....
```

Should `v-lazy` directive be somehow added as global directive under `src/vue/directives` ?

**Comment by sergejcodes** [comment]
`vue-lazyload` isn't compatible with Theme Lab v3 anymore, since Vue 3 is now in use and `vue-lazyload` only supports Vue 1 and 2.
